### ISSUE TITLE
Suggestion: Use another icon for project descriptions

### ISSUE THREAD

**Issue by tteltrab** [codemarq/fullStackPortfolio#6]
The "three dots" is usually meant for more options/preferences, etc. I'd use the info-sign glyph, it more clearly indicates to the user what they're getting. 
![image](https://cloud.githubusercontent.com/assets/1487463/22183859/a5a5d724-e095-11e6-82b9-6a54ba5e2123.png)

**Comment by codemarq** [comment]
broke this out into two issues.
